name: Jira closure

on:
  issues:
    types: [closed, deleted]

jobs:
  close-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login
        uses: atlassian/gajira-login@v2.0.0
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.KUSHAN_JIRA_API_TOKEN }}

      - name: Extract issue from title
        id: extract
        env:
          TITLE: ${{ github.event.issue.title }}
        run: |
          jira=$(echo -n $TITLE | awk '{print $1}' | set -e 's/://')
          echo $jira
          echo "KUSHAN"
          echo '::set-output name=jira::$jira'

      - name: Close issue
        uses: kushanzaveri/gajira-transition@add-fields-support
#        if: startsWith(steps.extract.outputs.jira, 'SNOW-')
        with:
          issue: ${{ steps.extract.outputs.jira }}
          transition: 'MOVE TO DONE'
          fields: '{
            "customfield_12860": {"id": "11506"},
            "customfield_10800": {"id": "-1"},
            "customfield_12500": {"id": "11302"},
            "customfield_12400": {"id": "-1"},
            "resolution": {"name": "Done"}
          }'
          update: '{ "comment": [ { "add": { "body" : "Closed on GitHub" } } ] }'
